import './launch-style.css';
import './brand.css';
import './evidence-style.css';
import { brandHeader } from './brand';
import proof from '../evidence/launch-demo-devnet.json';
import { escapeHtml as h, formatAmount } from './launch-ui';

document.querySelector<HTMLDivElement>('#app')!.innerHTML = `${brandHeader('evidence')}
<main id="main-content"><section class="intro"><div class="eyebrow">RECORDED DEVNET VERIFICATION</div><h1>A promise.<br>With receipts.</h1><div class="intro-aside"><p>One launch settled. One refunded.<br>Both ran through the real protocol.</p><p class="muted">Recorded evidence is separate from live account state. Open either launch to inspect its current state.</p></div></section>
<div class="notice">Synthetic devnet assets. Development review completed; no external audit or mainnet readiness certification.</div>
<section class="evidence-section"><div class="section-title"><h2>Two outcomes, independently inspectable</h2></div><div class="receipt-grid">${proof.launches.map((launch,i)=>`<article class="receipt"><span class="eyebrow">${i===0?'OPENING PURCHASE':'FULL REFUND'}</span><h3>${h(launch.name)}</h3><p class="receipt-amount">${formatAmount(launch.quoteSpent,6)} <small>quote spent</small></p><p>${i===0?`${formatAmount(launch.baseReceived,6)} OPEN received; allocations and unused funding claimed.`:'Minimum raise missed. No pool created; both deposits returned.'}</p><p class="muted">Unauthorized bid read denied during the private window: ${launch.privateReadDeniedDuringWindow?'verified':'not recorded'}.</p><a class="evidence-link" href="/launch.html?launch=${launch.launch}">Inspect launch ↗</a><details><summary>Transaction receipts (${launch.signatures.length})</summary><ol>${launch.signatures.map((signature,j)=>`<li><a href="https://explorer.solana.com/tx/${signature}?cluster=devnet" target="_blank" rel="noreferrer">Transaction ${j+1} ↗</a></li>`).join('')}</ol></details></article>`).join('')}</div></section>
<section class="evidence-section"><h2>What each layer does</h2><div class="architecture"><article><span>01</span><h3>MagicBlock</h3><p>Private ER permissions protect bids during bidding. Scoped VRF supplies allocation randomness. Closed bids return to Solana.</p></article><article><span>02</span><h3>Teek on Solana</h3><p>Immutable terms, public escrow, capped participation, pro-rata allocation, settlement deadlines, claims and refunds.</p></article><article><span>03</span><h3>Meteora DBC</h3><p>Pool creation and the shared opening purchase execute atomically. Public curve trading follows. Graduation is not demonstrated in these receipts.</p></article></div></section>
<section class="evidence-section boundaries"><div><h2>Privacy, precisely stated.</h2><p>Funding amounts, identities and transaction timing are public. Bid amounts stay confidential during the bidding window. Closing publishes bids and earlier edits.</p></div><div><h3>Prototype boundaries</h3><ul><li>Maximum 24 registered wallets per launch.</li><li>One shared purchase on a fixed curve; no limit-order price discovery.</li><li>Delegated bid recovery can be delayed by a Private ER outage.</li><li>Recorded launches have closed; participation needs a fresh window.</li></ul></div></section>
<section class="evidence-section"><h2>Source & development history</h2><p class="reading">Teek began as Tick in September 2026. The original batch-market engine is prior work. The October launch build adds private budget bids, immutable launch terms, DBC settlement, token and refund claims, and the launch interface. Event submissions must disclose the baseline and identify work completed during each event.</p><a class="evidence-link" href="https://github.com/IamHarrie-Labs/teek" target="_blank" rel="noreferrer">Source repository ↗</a><p class="muted">Reproduce with README.md and teek/LAUNCH_DEMO.md. Security findings and resolutions are documented in teek/SETTLEMENT_REVIEW.md. Recorded receipt values come from the repository’s launch-demo-devnet.json.</p></section>
<footer class="page-footer"><span>Private bids. One opening. Public proof.</span><a href="/launch.html">Open launch app ↗</a></footer></main>`;
