import './launch-style.css';
import './brand.css';
import './evidence-style.css';
import { brandHeader } from './brand';

document.querySelector<HTMLDivElement>('#app')!.innerHTML = `${brandHeader('evidence')}<main id="main-content">
<section class="intro"><div class="eyebrow">SUBMISSION BRIEF · DRAFT</div><h1>Private bids.<br>One opening.</h1><div class="intro-aside"><p>Teek pools private budget bids into one opening purchase on Meteora DBC, with enforceable terms and refunds.</p><a class="evidence-link" href="/evidence.html">Inspect recorded proof ↗</a></div></section>
<section class="evidence-section"><h2>Project description</h2><div class="reading"><p>Token launches ask buyers to compete at the first tradable moment. Teek gives participants a shared opening purchase instead: creators lock the launch terms, buyers fund public escrow, and bidders privately choose how much to commit during a defined window.</p><p>At close, accepted demand is capped and shared pro rata. Everyone participates in the same purchase and pays the same average price, including native curve fees. The Meteora DBC pool is created and bought in one atomic transaction. If demand misses the minimum or the launch is cancelled before settlement, participants can reclaim their deposits. Unused funding is refundable after success.</p><p>MagicBlock Private ER permissions protect bid amounts during bidding. MagicBlock scoped VRF supplies randomness for exact integer allocation. Solana holds escrow and enforces immutable terms, claims and refunds; Meteora provides the curve and subsequent public trading. Funding, identities and timing remain public. Closing exposes bids and earlier edits.</p><p>The devnet prototype has completed a successful opening and a failed-minimum launch with full refunds. Recorded receipts show unauthorized private reads denied during bidding, a real opening purchase, claimed allocations and returned deposits. The repository includes settlement tests and an independent development review. These are synthetic test assets; the protocol has no external audit or mainnet certification.</p><p>Our proposed customers are launchpad operators and token creators who want a coordinated entry window. Next steps are customer pilots, operational recovery work, external security review and validation of DBC partner-fee economics before a mainnet launch.</p></div></section>
<section class="evidence-section"><h2>Integration proof</h2><div class="architecture"><article><h3>MagicBlock</h3><p>Private ER bid permissions, scoped VRF, and return of closed state to Solana.</p></article><article><h3>Meteora</h3><p>Atomic DBC pool creation plus opening purchase, creator-rights transfer and token distribution.</p></article><article><h3>Solana</h3><p>Public escrow, immutable configuration, exact allocation, claims, cancellation and refunds.</p></article></div><p>Program: <a href="https://explorer.solana.com/address/B6eqSCBhokuZLKqBrzwhquUho183P3Fvu8pgC4a9PFkY?cluster=devnet" target="_blank" rel="noreferrer">B6eqSCBh…PkY ↗</a></p><a href="https://github.com/IamHarrie-Labs/teek" target="_blank" rel="noreferrer">Repository ↗</a></section>
<section class="evidence-section"><h2>Development disclosure</h2><p class="reading">Tick’s original batch engine and hosted ER market work began in September 2026. The October launch build adds private budget bids, immutable venue binding, atomic DBC settlement, token/refund claims and a launch frontend. Disclose the actual pre-event baseline for each competition; do not describe the entire repository as new event work.</p></section>
<section class="evidence-section"><h2>Product demo · 2 minutes 45 seconds</h2><ol class="reading"><li><strong>0:00–0:20:</strong> Explain private budget bids and the shared opening purchase.</li><li><strong>0:20–0:50:</strong> Inspect the recorded success launch’s immutable cap, output floor and outcome.</li><li><strong>0:50–1:20:</strong> Show recorded privacy proof and explain public funding and post-close disclosure. Use a fresh launch to demonstrate live bid edits.</li><li><strong>1:20–1:55:</strong> Show DBC settlement receipts, allocations and claims.</li><li><strong>1:55–2:20:</strong> Inspect the refund launch: zero quote spent, no pool, full deposits returned.</li><li><strong>2:20–2:45:</strong> Explain the three integrations and prototype boundaries.</li></ol></section>
<section class="evidence-section"><h2>Before submitting</h2><div class="notice">This brief is prepared locally. It is not a submitted entry or a claim that every eligibility condition is met.</div><ul class="reading"><li>Publish a stable public demo URL; localhost is not accessible to judges.</li><li>Record the product-demo video and a separate Colosseum presentation video.</li><li>Confirm repository visibility or grant the required reviewer access.</li><li>Add verified team backgrounds, location, contact details and payout wallet.</li><li>Add actual customer interviews, demand evidence and distribution plan; none is claimed here.</li><li>Confirm each sponsor’s exact current requirements, and submit separately where required.</li><li>Solami/RPC Fast remain conditional; no completed mainnet integration is claimed.</li></ul></section>
<footer class="page-footer"><span>Prepared from repository evidence · October 8, 2026</span><a href="/launch.html">Open launch app ↗</a></footer></main>`;
